// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unitd.proto

package unitd

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ConnInfo struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnInfo) Reset()         { *m = ConnInfo{} }
func (m *ConnInfo) String() string { return proto.CompactTextString(m) }
func (*ConnInfo) ProtoMessage()    {}
func (*ConnInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{1}
}

func (m *ConnInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnInfo.Unmarshal(m, b)
}
func (m *ConnInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnInfo.Marshal(b, m, deterministic)
}
func (m *ConnInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnInfo.Merge(m, src)
}
func (m *ConnInfo) XXX_Size() int {
	return xxx_messageInfo_ConnInfo.Size(m)
}
func (m *ConnInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnInfo proto.InternalMessageInfo

func (m *ConnInfo) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ConnInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *ConnInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ClientMsg struct {
	// Types that are valid to be assigned to Message:
	//	*ClientMsg_Entry
	//	*ClientMsg_Query
	//	*ClientMsg_Sub
	//	*ClientMsg_Pub
	Message              isClientMsg_Message `protobuf_oneof:"Message"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ClientMsg) Reset()         { *m = ClientMsg{} }
func (m *ClientMsg) String() string { return proto.CompactTextString(m) }
func (*ClientMsg) ProtoMessage()    {}
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{2}
}

func (m *ClientMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMsg.Unmarshal(m, b)
}
func (m *ClientMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMsg.Marshal(b, m, deterministic)
}
func (m *ClientMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMsg.Merge(m, src)
}
func (m *ClientMsg) XXX_Size() int {
	return xxx_messageInfo_ClientMsg.Size(m)
}
func (m *ClientMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMsg proto.InternalMessageInfo

type isClientMsg_Message interface {
	isClientMsg_Message()
}

type ClientMsg_Entry struct {
	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3,oneof"`
}

type ClientMsg_Query struct {
	Query *Query `protobuf:"bytes,2,opt,name=query,proto3,oneof"`
}

type ClientMsg_Sub struct {
	Sub *Sub `protobuf:"bytes,3,opt,name=sub,proto3,oneof"`
}

type ClientMsg_Pub struct {
	Pub *Pub `protobuf:"bytes,4,opt,name=pub,proto3,oneof"`
}

func (*ClientMsg_Entry) isClientMsg_Message() {}

func (*ClientMsg_Query) isClientMsg_Message() {}

func (*ClientMsg_Sub) isClientMsg_Message() {}

func (*ClientMsg_Pub) isClientMsg_Message() {}

func (m *ClientMsg) GetMessage() isClientMsg_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ClientMsg) GetEntry() *Entry {
	if x, ok := m.GetMessage().(*ClientMsg_Entry); ok {
		return x.Entry
	}
	return nil
}

func (m *ClientMsg) GetQuery() *Query {
	if x, ok := m.GetMessage().(*ClientMsg_Query); ok {
		return x.Query
	}
	return nil
}

func (m *ClientMsg) GetSub() *Sub {
	if x, ok := m.GetMessage().(*ClientMsg_Sub); ok {
		return x.Sub
	}
	return nil
}

func (m *ClientMsg) GetPub() *Pub {
	if x, ok := m.GetMessage().(*ClientMsg_Pub); ok {
		return x.Pub
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientMsg_Entry)(nil),
		(*ClientMsg_Query)(nil),
		(*ClientMsg_Sub)(nil),
		(*ClientMsg_Pub)(nil),
	}
}

type ServerMsg struct {
	// Types that are valid to be assigned to Message:
	//	*ServerMsg_Info
	//	*ServerMsg_Data
	Message              isServerMsg_Message `protobuf_oneof:"Message"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ServerMsg) Reset()         { *m = ServerMsg{} }
func (m *ServerMsg) String() string { return proto.CompactTextString(m) }
func (*ServerMsg) ProtoMessage()    {}
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{3}
}

func (m *ServerMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMsg.Unmarshal(m, b)
}
func (m *ServerMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMsg.Marshal(b, m, deterministic)
}
func (m *ServerMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMsg.Merge(m, src)
}
func (m *ServerMsg) XXX_Size() int {
	return xxx_messageInfo_ServerMsg.Size(m)
}
func (m *ServerMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMsg proto.InternalMessageInfo

type isServerMsg_Message interface {
	isServerMsg_Message()
}

type ServerMsg_Info struct {
	Info *Info `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type ServerMsg_Data struct {
	Data *Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ServerMsg_Info) isServerMsg_Message() {}

func (*ServerMsg_Data) isServerMsg_Message() {}

func (m *ServerMsg) GetMessage() isServerMsg_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ServerMsg) GetInfo() *Info {
	if x, ok := m.GetMessage().(*ServerMsg_Info); ok {
		return x.Info
	}
	return nil
}

func (m *ServerMsg) GetData() *Data {
	if x, ok := m.GetMessage().(*ServerMsg_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerMsg_Info)(nil),
		(*ServerMsg_Data)(nil),
	}
}

type Entry struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{4}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Entry) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Query struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{5}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Query) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Sub struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sub) Reset()         { *m = Sub{} }
func (m *Sub) String() string { return proto.CompactTextString(m) }
func (*Sub) ProtoMessage()    {}
func (*Sub) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{6}
}

func (m *Sub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sub.Unmarshal(m, b)
}
func (m *Sub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sub.Marshal(b, m, deterministic)
}
func (m *Sub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sub.Merge(m, src)
}
func (m *Sub) XXX_Size() int {
	return xxx_messageInfo_Sub.Size(m)
}
func (m *Sub) XXX_DiscardUnknown() {
	xxx_messageInfo_Sub.DiscardUnknown(m)
}

var xxx_messageInfo_Sub proto.InternalMessageInfo

func (m *Sub) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

type Pub struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pub) Reset()         { *m = Pub{} }
func (m *Pub) String() string { return proto.CompactTextString(m) }
func (*Pub) ProtoMessage()    {}
func (*Pub) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{7}
}

func (m *Pub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pub.Unmarshal(m, b)
}
func (m *Pub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pub.Marshal(b, m, deterministic)
}
func (m *Pub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pub.Merge(m, src)
}
func (m *Pub) XXX_Size() int {
	return xxx_messageInfo_Pub.Size(m)
}
func (m *Pub) XXX_DiscardUnknown() {
	xxx_messageInfo_Pub.DiscardUnknown(m)
}

var xxx_messageInfo_Pub proto.InternalMessageInfo

func (m *Pub) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Pub) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Info struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{8}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Info) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type Data struct {
	Topic                []byte   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_2581e9e1a4f3b0d3, []int{9}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Data) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "unitd.Empty")
	proto.RegisterType((*ConnInfo)(nil), "unitd.ConnInfo")
	proto.RegisterType((*ClientMsg)(nil), "unitd.ClientMsg")
	proto.RegisterType((*ServerMsg)(nil), "unitd.ServerMsg")
	proto.RegisterType((*Entry)(nil), "unitd.Entry")
	proto.RegisterType((*Query)(nil), "unitd.Query")
	proto.RegisterType((*Sub)(nil), "unitd.Sub")
	proto.RegisterType((*Pub)(nil), "unitd.Pub")
	proto.RegisterType((*Info)(nil), "unitd.Info")
	proto.RegisterType((*Data)(nil), "unitd.Data")
}

func init() { proto.RegisterFile("unitd.proto", fileDescriptor_2581e9e1a4f3b0d3) }

var fileDescriptor_2581e9e1a4f3b0d3 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0xa5, 0x4a, 0x1b, 0x47, 0x63, 0x43, 0xc3, 0x92, 0x83, 0x70, 0xa0, 0xb4, 0x4b, 0x0e,
	0x81, 0x82, 0x09, 0x0e, 0x6d, 0xef, 0x49, 0x03, 0xce, 0x21, 0x90, 0x4a, 0xf4, 0xd2, 0x16, 0xca,
	0xca, 0xda, 0x04, 0x51, 0x7b, 0x57, 0x59, 0x8d, 0x5a, 0xf4, 0x0e, 0x7d, 0x8a, 0x3e, 0x69, 0x99,
	0x91, 0x94, 0x36, 0x25, 0xee, 0xcd, 0xdf, 0xfc, 0xbe, 0xf9, 0xa3, 0xf1, 0x2c, 0x4c, 0x5b, 0x5b,
	0x61, 0xb9, 0xa8, 0xbd, 0x43, 0x27, 0x05, 0x0b, 0x35, 0x01, 0x71, 0xb9, 0xad, 0xb1, 0x53, 0x9f,
	0x61, 0xff, 0xc2, 0x59, 0x7b, 0x65, 0x6f, 0x9d, 0x3c, 0x82, 0x64, 0xbd, 0xa9, 0x8c, 0xc5, 0xaf,
	0x55, 0x99, 0x86, 0x2f, 0xc3, 0x93, 0x24, 0xdb, 0xef, 0x03, 0x57, 0xa5, 0x4c, 0x61, 0x62, 0x0d,
	0xfe, 0x70, 0xfe, 0x5b, 0xfa, 0x8c, 0xd1, 0x28, 0x89, 0xe8, 0xb2, 0xf4, 0xa6, 0x69, 0xd2, 0xa8,
	0x27, 0x83, 0x54, 0xbf, 0x42, 0x48, 0x2e, 0xb8, 0xc0, 0x75, 0x73, 0x27, 0x8f, 0x41, 0x18, 0x8b,
	0xbe, 0xe3, 0xd2, 0xd3, 0xe5, 0x6c, 0xd1, 0xcf, 0x75, 0x49, 0xb1, 0x55, 0x90, 0xf5, 0x90, 0x5c,
	0xf7, 0xad, 0xf1, 0x1d, 0x77, 0xf9, 0xe3, 0xfa, 0x40, 0x31, 0x72, 0x31, 0x94, 0x2f, 0x20, 0x6a,
	0xda, 0x82, 0xfb, 0x4d, 0x97, 0x30, 0x78, 0xf2, 0xb6, 0x58, 0x05, 0x19, 0x01, 0xe2, 0x75, 0x5b,
	0xa4, 0xf1, 0x23, 0x7e, 0xd3, 0xf3, 0xba, 0x2d, 0xce, 0x13, 0x98, 0x5c, 0x9b, 0xa6, 0xd1, 0x77,
	0x46, 0x7d, 0x81, 0x24, 0x37, 0xfe, 0xbb, 0xf1, 0x34, 0xe3, 0x2b, 0x88, 0x2b, 0x7b, 0xeb, 0x86,
	0x11, 0xa7, 0x43, 0x22, 0x6d, 0x67, 0x15, 0x64, 0x8c, 0xc8, 0x52, 0x6a, 0xd4, 0xc3, 0x7c, 0xa3,
	0xe5, 0xbd, 0x46, 0x4d, 0x16, 0x42, 0x7f, 0x57, 0x7f, 0x07, 0x82, 0x3f, 0x50, 0x1e, 0x82, 0x40,
	0x57, 0x57, 0x6b, 0x2e, 0x3d, 0xcb, 0x7a, 0x41, 0xbb, 0xab, 0x75, 0xb7, 0x71, 0xba, 0xe4, 0x7a,
	0xb3, 0x6c, 0x94, 0xea, 0x0c, 0x04, 0x7f, 0xf3, 0x8e, 0xc4, 0x43, 0x10, 0x9b, 0x6a, 0x5b, 0x21,
	0xa7, 0x89, 0xac, 0x17, 0xea, 0x08, 0xa2, 0xbc, 0x2d, 0x9e, 0x4e, 0x51, 0x6f, 0x20, 0xba, 0xd9,
	0x05, 0xff, 0x33, 0xc8, 0x02, 0x62, 0xbe, 0x8e, 0xa7, 0xf3, 0x0e, 0x20, 0x6a, 0xcc, 0x3d, 0xe7,
	0xc4, 0x19, 0xfd, 0x54, 0x6f, 0x21, 0xa6, 0x65, 0xec, 0xee, 0xb3, 0x76, 0x16, 0x8d, 0xc5, 0xb1,
	0xcf, 0x20, 0x97, 0x3f, 0x43, 0x10, 0x1f, 0x69, 0x97, 0xf2, 0x35, 0x88, 0x1c, 0xb5, 0x47, 0xf9,
	0x7c, 0x58, 0xee, 0x78, 0xa1, 0xf3, 0x7f, 0x03, 0x2a, 0x90, 0xa7, 0xb0, 0x97, 0xa3, 0x37, 0x7a,
	0x2b, 0x0f, 0x46, 0x38, 0x5e, 0xdc, 0x7c, 0x8c, 0x3c, 0xfc, 0xbf, 0x27, 0xe1, 0x69, 0x28, 0x8f,
	0x21, 0xce, 0xd1, 0xd5, 0xf2, 0xe1, 0x00, 0xe9, 0x21, 0xcc, 0x1f, 0x29, 0x15, 0x9c, 0x4f, 0x3e,
	0xf5, 0x4f, 0xa5, 0xd8, 0xe3, 0x87, 0x73, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x1c, 0xe6,
	0xe2, 0x47, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UnitdClient is the client API for Unitd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnitdClient interface {
	Start(ctx context.Context, in *ConnInfo, opts ...grpc.CallOption) (*ConnInfo, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Unitd_StreamClient, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type unitdClient struct {
	cc *grpc.ClientConn
}

func NewUnitdClient(cc *grpc.ClientConn) UnitdClient {
	return &unitdClient{cc}
}

func (c *unitdClient) Start(ctx context.Context, in *ConnInfo, opts ...grpc.CallOption) (*ConnInfo, error) {
	out := new(ConnInfo)
	err := c.cc.Invoke(ctx, "/unitd.Unitd/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitdClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Unitd_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Unitd_serviceDesc.Streams[0], "/unitd.Unitd/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &unitdStreamClient{stream}
	return x, nil
}

type Unitd_StreamClient interface {
	Send(*ClientMsg) error
	Recv() (*ServerMsg, error)
	grpc.ClientStream
}

type unitdStreamClient struct {
	grpc.ClientStream
}

func (x *unitdStreamClient) Send(m *ClientMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *unitdStreamClient) Recv() (*ServerMsg, error) {
	m := new(ServerMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *unitdClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/unitd.Unitd/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnitdServer is the server API for Unitd service.
type UnitdServer interface {
	Start(context.Context, *ConnInfo) (*ConnInfo, error)
	Stream(Unitd_StreamServer) error
	Stop(context.Context, *Empty) (*Empty, error)
}

// UnimplementedUnitdServer can be embedded to have forward compatible implementations.
type UnimplementedUnitdServer struct {
}

func (*UnimplementedUnitdServer) Start(ctx context.Context, req *ConnInfo) (*ConnInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedUnitdServer) Stream(srv Unitd_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (*UnimplementedUnitdServer) Stop(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}

func RegisterUnitdServer(s *grpc.Server, srv UnitdServer) {
	s.RegisterService(&_Unitd_serviceDesc, srv)
}

func _Unitd_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitdServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unitd.Unitd/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitdServer).Start(ctx, req.(*ConnInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unitd_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UnitdServer).Stream(&unitdStreamServer{stream})
}

type Unitd_StreamServer interface {
	Send(*ServerMsg) error
	Recv() (*ClientMsg, error)
	grpc.ServerStream
}

type unitdStreamServer struct {
	grpc.ServerStream
}

func (x *unitdStreamServer) Send(m *ServerMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *unitdStreamServer) Recv() (*ClientMsg, error) {
	m := new(ClientMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Unitd_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitdServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unitd.Unitd/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitdServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Unitd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "unitd.Unitd",
	HandlerType: (*UnitdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Unitd_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Unitd_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Unitd_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "unitd.proto",
}
